### ISSUE TITLE
Calendar swipe issue

### ISSUE THREAD

**Issue by ValhallaSkies** [arnowelzel/periodical#48] opened 2018-07-28 00:33 UTC
When swiping the calendar the period input disappears. It stays as entered while using the forward/back arrows.

**Comment by arnowelzel** [comment] 2018-07-28 23:05
@ValhallaSkies Can you please explain step by step how to reproduce this? Thank you.

**Comment by ValhallaSkies** [comment] 2018-07-28 23:15
Step 1: Select days for period. 
Step 2: Swipe to next month.
Step 3: Swipe back to previous month. Entered period dates no longer show. 

Step 4: Use back/forward buttons, entered period dates show.

**Comment by arnowelzel** [comment] 2018-07-29 10:08
I just verified these actions. Sorry, I can't reproduce that with Android 7.1 or 8.0. Maybe I missed something?

I tap a day in the (so far empty) calendar, Periodical asks if the day should be marked as "Period" and I select "YES". The day get's marked:

<img src="https://user-images.githubusercontent.com/6613614/43365063-fbee2f74-9326-11e8-95b4-287cc704ae11.png" width="170" />

Then I swipe to the left to change to the next month:

<img src="https://user-images.githubusercontent.com/6613614/43365070-1fed4b94-9327-11e8-8f2f-995491eb9346.png" width="170" />

And then I swipe again to the right and the old view appears again, including the already marked day:

<img src="https://user-images.githubusercontent.com/6613614/43365117-03acb9a0-9328-11e8-9f75-59f925c9ab68.png" width="170" />

**Comment by ValhallaSkies** [comment] 2018-07-29 19:04
I tested on Ver 19. Ill try on something newer.

**Comment by arnowelzel** [comment] 2018-07-30 06:12
I'm not aware of any bug which may cause the behaviour you described. However - version 19 is really old (more than 3 years) and you should definetely test the current release.

**Comment by arnowelzel** [comment] 2018-08-09 14:35
@ValhallaSkies Did you have a chance to test the latest version yet?

**Comment by arnowelzel** [comment] 2018-10-21 13:02
Since there is not feedback yet and I can't reproduce this, I'll close this issue.

**Closed by arnowelzel** 2018-10-21 13:02 UTC
